// ═════════════════════════════════════════════════════════════════════════════
// GQA_fwd_v62.cu — STANDALONE precision-check + latency-benchmark harness
// for the forward kernel v62 (GQA_fwd_ref.cu).
//
// Follows the EXACT same pattern as GQA_bwd_v44.cu:
//   1. loads reference data from data/gqa_fwd_*.bin (generated by
//      precision/baseline_gqa_fwd.py)
//   2. runs launch_gqa_v62() on the inputs
//   3. compares O and LSE vs reference using reportPrecision / checkResult
//   4. benchmarks latency using benchmarkKernel / displayStats
//
// sm_90a (Hopper H100/H200).
// ═════════════════════════════════════════════════════════════════════════════

#include <cuda_bf16.h>
#include <cuda.h>
#include <cuda_runtime.h>
#include <cstdio>
#include <cstdint>
#include <cmath>
#include <iostream>
#include <vector>

#include "utils/kernelUtils.cuh"
#include "utils/kernelBench.cuh"

// Pull in the kernel + launcher from GQA_fwd_ref.cu.
// That file is entirely self-contained (constants, helpers, kernel, launcher
// all in one TU), so including it gives us launch_gqa_v62() and
// gqa_v62_smem_bytes() without code duplication.
//
// NOTE: GQA_fwd_ref.cu lives in the same directory, and its own
// #include "gqa_v62.cuh" resolves to the stub header we ship alongside.
#include "GQA_fwd_ref.cu"

// ═════════════════════════════════════════════════════════════════════════════
// main — precision-check + latency-benchmark for B=2 and B=4
// ═════════════════════════════════════════════════════════════════════════════
static void run_for_B(int B) {
    constexpr int Hq = 12, Hkv = 4, G = Hq / Hkv;
    constexpr int S = 4096, D = 128;
    const float scale = 1.0f / sqrtf((float)D);

    const size_t Nq   = (size_t)B * Hq  * S * D;
    const size_t Nkv  = (size_t)B * Hkv * S * D;
    const size_t Nlse = (size_t)B * Hq  * S;

    // ── check that reference files exist with the right sizes ────────────
    auto fileSz = [](const char *p, size_t n) -> bool {
        FILE *f = fopen(p, "rb"); if (!f) return false;
        fseek(f, 0, SEEK_END); size_t b = (size_t)ftell(f); fclose(f);
        return b == n * sizeof(float);
    };
    if (!fileSz("data/gqa_fwd_q.bin",   Nq)  ||
        !fileSz("data/gqa_fwd_k.bin",   Nkv) ||
        !fileSz("data/gqa_fwd_v.bin",   Nkv) ||
        !fileSz("data/gqa_fwd_o.bin",   Nq)  ||
        !fileSz("data/gqa_fwd_lse.bin", Nlse)) {
        printf("[B=%d] reference size mismatch — run baseline_gqa_fwd.py for B=%d, skipping\n", B, B);
        return;
    }

    // ── load inputs + reference outputs ──────────────────────────────────
    std::vector<__nv_bfloat16> h_Q(Nq), h_K(Nkv), h_V(Nkv);
    std::vector<float>         h_O_ref(Nq), h_LSE_ref(Nlse);

    auto loadBF16 = [](const char *p, std::vector<__nv_bfloat16> &dst, size_t n){
        std::vector<float> tmp(n); loadBin(p, tmp.data(), n);
        for (size_t i = 0; i < n; ++i) dst[i] = __float2bfloat16(tmp[i]);
    };
    loadBF16("data/gqa_fwd_q.bin", h_Q,  Nq);
    loadBF16("data/gqa_fwd_k.bin", h_K,  Nkv);
    loadBF16("data/gqa_fwd_v.bin", h_V,  Nkv);
    loadBin("data/gqa_fwd_o.bin",   h_O_ref.data(),   Nq);
    loadBin("data/gqa_fwd_lse.bin", h_LSE_ref.data(), Nlse);

    // ── allocate device memory ───────────────────────────────────────────
    __nv_bfloat16 *d_Q, *d_K, *d_V, *d_O;
    float *d_LSE;
    CUDA_CHECK(cudaMalloc(&d_Q,   Nq   * sizeof(__nv_bfloat16)));
    CUDA_CHECK(cudaMalloc(&d_K,   Nkv  * sizeof(__nv_bfloat16)));
    CUDA_CHECK(cudaMalloc(&d_V,   Nkv  * sizeof(__nv_bfloat16)));
    CUDA_CHECK(cudaMalloc(&d_O,   Nq   * sizeof(__nv_bfloat16)));
    CUDA_CHECK(cudaMalloc(&d_LSE, Nlse * sizeof(float)));
    CUDA_CHECK(cudaMemcpy(d_Q, h_Q.data(), Nq  * sizeof(__nv_bfloat16), cudaMemcpyHostToDevice));
    CUDA_CHECK(cudaMemcpy(d_K, h_K.data(), Nkv * sizeof(__nv_bfloat16), cudaMemcpyHostToDevice));
    CUDA_CHECK(cudaMemcpy(d_V, h_V.data(), Nkv * sizeof(__nv_bfloat16), cudaMemcpyHostToDevice));

    // ── run kernel ───────────────────────────────────────────────────────
    launch_gqa_v62(d_Q, d_K, d_V, d_O, d_LSE, B, Hq, Hkv, S, scale, 0);
    CUDA_CHECK(cudaGetLastError());
    CUDA_CHECK(cudaDeviceSynchronize());

    // ── download + compare ───────────────────────────────────────────────
    {
        std::vector<__nv_bfloat16> h_O_gpu(Nq);
        std::vector<float>         h_LSE_gpu(Nlse);
        CUDA_CHECK(cudaMemcpy(h_O_gpu.data(),   d_O,   Nq   * sizeof(__nv_bfloat16), cudaMemcpyDeviceToHost));
        CUDA_CHECK(cudaMemcpy(h_LSE_gpu.data(), d_LSE, Nlse * sizeof(float),         cudaMemcpyDeviceToHost));

        std::vector<float> of(Nq);
        for (size_t i = 0; i < Nq; ++i) of[i] = __bfloat162float(h_O_gpu[i]);

        printf("── V62 forward standalone  B=%d ──\n", B);
        reportPrecision("  O ",  h_O_ref.data(),   of.data(),           Nq);
        reportPrecision("  LSE", h_LSE_ref.data(), h_LSE_gpu.data(),    Nlse);
        std::cout << "  O:   "; checkResult(h_O_ref.data(),   of.data(),         Nq,   2e-2f, 2e-2f);
        std::cout << "  LSE: "; checkResult(h_LSE_ref.data(), h_LSE_gpu.data(), Nlse, 2e-2f, 2e-2f);
        std::cout << "\n";
    }

    // ── benchmark ────────────────────────────────────────────────────────
    // Forward FLOPs (causal): 4 * B * Hq * S * S * D / 2
    const long long fwd_flops = 2LL * B * Hq * (long long)S * S * D;
    {
        char label[128];
        snprintf(label, sizeof(label),
                 "V62 forward standalone  B=%d  persistent warp-specialised  (Hopper SM_90)", B);
        KernelStats s = benchmarkKernel(
            [&](){ launch_gqa_v62(d_Q, d_K, d_V, d_O, d_LSE, B, Hq, Hkv, S, scale, 0); },
            100, 10, fwd_flops);
        displayStats(label, s);
    }

    // ── cleanup ──────────────────────────────────────────────────────────
    CUDA_CHECK(cudaFree(d_Q));
    CUDA_CHECK(cudaFree(d_K));
    CUDA_CHECK(cudaFree(d_V));
    CUDA_CHECK(cudaFree(d_O));
    CUDA_CHECK(cudaFree(d_LSE));
}

int main() {
    std::cout << "GQA Forward V62 — standalone precision + latency  [Hopper SM_90 / H200]\n";
    std::cout << "Prerequisite: python precision/baseline_gqa_fwd.py (per B)\n\n";
    run_for_B(2);
    run_for_B(4);
    return 0;
}
